name: Trigger sync

on: 
  repository_dispatch:
    types: [main_updated]

jobs:
  trigger-sync:
    if: github.repository == 'forestream/ci-cd-copied'
    runs-on: ubuntu-latest
    steps:
      - run: echo 'sync'
